const fontFamilies = [
  // "Apple SD Gothic Neo",
  "Arial",
  "Arial Black",
  "Arial Narrow",
  // "Avant Garde",
  // "Bookman",
  // "Calibri",
  // "Candara",
  // "Century Gothic",
  "Copperplate",
  "Courier New",
  "Didot",
  // "Franklin Gothic Medium",
  // "Frutiger",
  "Futura",
  // "Garamond",
  "Geneva",
  "Georgia",
  "Gill Sans",
  "Helvetica",
  "Helvetica Neue",
  "Hiragino Sans",
  // "Hoefler Text",
  "Impact",
  // "Lato",
  // "Lucida Console",
  "Lucida Grande",
  // "Lucida Sans Unicode",
  // "Montserrat",
  // "Myriad",
  "Open Sans",
  "Optima",
  // "Oswald",
  "PT Sans",
  "Palatino",
  // "Raleway",
  // "Roboto",
  "Rockwell",
  // "Segoe UI",
  // "Source Sans Pro",
  "Tahoma",
  "Thonburi",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana"
  // "Verdana Pro"
];

export default fontFamilies;
